#!/usr/bin/env bash

# Get location of repository by reading the symlink
# WARNING: It asumes symlink name as `dcc-tools`
dt_exec_symlink=$(command -v dcc-tools)
dt_exec_path=$(readlink $dt_exec_symlink)
TOOLS_DIR=${dt_exec_path%%/dcc-tools}

BIN_DIR="$HOME/.local/bin"

# Set git command
git_cmd="git -C $TOOLS_DIR"

function myhelp() {

    printf -- "Herramientas para el servidor del dcc\n"
    printf -- "  status      Revisa el estado del repositorio\n"
    printf -- "  fetch       Descarga actualizaciones\n"
    printf -- "  pull        Aplica las actualizaciones\n"
    printf -- "  os-release  Información sobre el servidor\n"
    printf -- "  install     Instala una herramienta\n"
    printf -- "  remove      Elimina una herramienta\n"
    printf -- "  list        Lista herramientas disponibles\n"

}

function edit_tools() {

    local mode=$1
    local tool=$2

    if [[ -z $tool ]] ; then
        printf -- "ERROR: No tool selected\n" 1>&2
        exit

    elif [[ $tool == "imprime" ]] ; then
        :

    elif [[ $tool == "zola" ]] ; then
        if [[ ! -f $TOOLS/zola ]] ; then
            $TOOLS_DIR/zola-fetch install $TOOLS_DIR
        fi

    else
        printf -- "ERROR: ${tool}: unknown tool\n" 1>&2
        exit
    fi

    if [[ $mode == "install" ]] ; then
        ln -s $TOOLS_DIR/$tool $BIN_DIR/$tool

    elif [[ $mode == "remove" ]] ; then
        rm $BIN_DIR/$tool
    fi

}

for arg in "$@"
do
    case $arg in
        help|-h|--help)
            shift
            myhelp
            ;;
        status)
            shift
            $git_cmd status
            exit
            ;;
        fetch)
            shift
            $git_cmd fetch
            exit
            ;;
        pull)
            shift
            $git_cmd pull
            exit
            ;;
        os-release)
            shift
            cat /etc/os-release
            exit
            ;;
        install)
            shift
            edit_tools "install" $1
            exit
            ;;
        remove)
            shift
            edit_tools "remove" $1
            exit
            ;;
        *)
            ;;
    esac
done
