#!/usr/bin/env bash

STU_FILE="$1"
INSTALL_DIR="$2"
BIN_DIR="$3"

mkdir -p "$INSTALL_DIR"
cd $INSTALL_DIR

source "$STU_FILE"

for _s in "${source[@]}" ; do
    curl --output /dev/null --silent --head --fail "$_s"
    if [[ $? -ne 0 ]] ; then
        printf -- 'ERROR: %s: url not valid\n' "$(basename $stubuild)" 
    fi
    curl -s -L -O "$_s"
done

tar xf "${stuname}-${stuver}.tar.xz"

cd "${stuname}-${stuver}"

build

dinstall

for i in ${bin[@]} ; do
    ln -sf "${INSTALL_DIR}/bin/$i" "${BIN_DIR}/$i"
    chmod "${BIN_DIR/$i}"
done
