#!/usr/bin/env bash

install_file=$1
bucket_root=$2

source $install_file

INSTALL_DIR="${bucket_root}/${pkgname}_dir"

## The following functions are public
##
## - src_verify
## - src_prepare
## - src_build
## - src_check
## - src_package

function mktool_prepare() {

    printf -- 'debug: run: mktool_prepare\n'

    mkdir -p "$INSTALL_DIR"

}

function mktool_download() {

    printf -- 'debug:run: mktool_download\n'

    curl --output /dev/null --silent --head --fail "${url}"

    if [[ $? -ne 0 ]] ; then
        printf -- 'ERROR: mktool: %s: invalid url\n' "$pkgname"
    fi

    (
    cd "$INSTALL_DIR"
    curl -s -L -O "${url}"
    )

}

function mktool_extract() {

    printf -- 'debug: run: mktool_extract\n'

}
