#!/usr/bin/env bash

# dcc-tools assumes this places
src_dir="$HOME/.local/src/dcc-tools"
bin_dir="$HOME/.local/bin"

function myhelp() {

    printf -- "Script para publicar sitio web en el dcc\n"
    printf -- "  --help    - Imprime este mensaje de ayuda\n"
    printf -- "  --archive - Archiva la versión anterior del sitio\n"
    printf -- "  --perms   - Establece permisos de directorios\n"
    printf -- "  --setup   - Alias de '--archive --perms'\n"

}

function archive_webpage() {

    # check if path exists
    if [[ -d "$HOME/public_www" ]] ; then
        now=$(date +%Y-%m-%d-%H-%M)
        mkdir -p "$HOME/public_www.old"
        mv "$HOME/public_www" "$HOME/public_www.old/$now"
    fi

}

function chmod_website() {

    # permissions for apache
    chmod o+x  "$HOME"
    chmod -R o+x "$HOME/public_www"
    chmod -R go+r "$HOME/public_www"

}

function setup_webpage() {

    archive_webpage
    mkdir "$HOME/public_www"
    chmod_website

}

for arg in "$@"
do
    case $arg in
        --help)
            shift
            myhelp
            ;;
        --archive)
            shift
            archive_webpage
            exit
            ;;
        --chmod|--perms)
            shift
            chmod_website
            exit
            ;;
        --setup)
            shift
            setup_webpage
            exit
            ;;
        *)
            ;;
    esac
done
