#!/usr/bin/env bash

# dcc-tools assumes this places
src_dir="$HOME/.local/src/dcc-tools"
bin_dir="$HOME/.local/bin"

function install_zola() {

    # short names
    gh_url="https://github.com/getzola/zola"
    distro="unknown-linux-gnu"

    # get latest version url
    zola_url=$(curl -w "%{url_effective}\n" -I -L -s -S ${gh_url}/releases/latest -o /dev/null)

    # get latest tag
    zola_tag=${zola_url##*/}

    # create cache
    mkdir ${src_dir}/cache

    # download binary file
    curl -s -L ${gh_url}/releases/download/${zola_tag}/zola-${zola_tag}-x86_64-${distro}.tar.gz --output ${src_dir}/cache/zola.tar.gz

    # extract binary file to exec path
    tar -xf ${src_dir}/cache/zola.tar.gz -C ${bin_dir}

    # clean cache
    rm ${src_dir}/cache/zola.tar.gz
    rmdir ${src_dir}/cache

}

function deploy_webpage() {

    root_dir=$1

    # check src code path
    if [[ -z ${root_dir} ]] ; then
        printf "Error: Debes especificar dónde está el source code de tu sitio\n"
        exit
    fi

    # archive old website
    if [[ -d ${HOME}/public_www ]] ; then
        now=$(date +%Y-%m-%d-%H-%M)
        mv ${HOME}/public_www ${HOME}/public_www.${now}
        mkdir ${HOME}/public_www
    fi

    # deploy website
    zola -r ${root_dir} build -o ${HOME}/public_www
    chmod -R go+r $HOME/public_www

}
for arg in "$@"
do
    case $arg in
        --install)
            shift
            install_zola
            exit
            ;;
        --deploy)
            shift
            deploy_webpage $1
            shift
            exit
            ;;
        *)
            ;;
    esac
done
