#!/usr/bin/env bash

function bucket_add() {

    local name="$1"
    local url="$2"

    if [[ -z $name ]] ; then
        printf -- 'error: bucket name not provided\n'
        exit
    fi

    local is_official=$(grep "$name" $CS_KNOWN_BUCKETS)

    if [[ -z $url && -z $is_official ]] ; then
        printf -- 'error: two parameters required\n'
        exit

    elif [[ -n $url && -z $is_official ]] ; then
        local protocol=$(printf -- "$url" | cut -d ':' -f1)
        case $protocol in
            https|http)
                ;;
            *)
                printf -- 'error: %s: protocol not supported\n' "$protocol"
                exit
                ;;
        esac

    elif [[ -z $url && -n $is_official ]] ; then
        url="${is_official##*::}"
        printf -- 'info: known bucket\n'
        printf -- 'info: %s\n' "$url"

    elif [[ -n $url && -n $is_official ]] ; then
        printf -- 'warning: overriding a known bucket\n'
    fi

    git clone "$url" "${CS_BUCKETS_DIR}/${name}"

}

function bucket_list() {

    local arrayBuckets=()
    readarray -t arrayBuckets < <(find "${CS_BUCKETS_DIR}" -maxdepth 1 -mindepth 1 -type d -printf "%f\n")

    if [[ "${#arrayBuckets[@]}" -eq 0 ]] ; then
        printf -- 'There are no buckets installed\n'
        exit
    fi

    for b in "${arrayBuckets[@]}" ; do
        printf -- '%s\n' "$b"
    done

}

function bucket_remove() {

    local target="$1"

    if [[ -z "$target" ]] ; then
        printf -- 'error: bucket name not specified\n'
        exit
    fi

    local arrayBuckets=()
    readarray -t arrayBuckets < <($CS_NAME bucket list)

    if [[ "${#arrayBuckets[@]}" -eq 0 ]] ; then
        printf -- 'error: there are no buckets added\n'
        exit
    fi

    for b in "${arrayBuckets[@]}" ; do
        if [[ "$target" == "$b" ]] ; then
            rm -rf "${CS_BUCKETS_DIR}/${target}"
            printf -- 'Bucket %s removed succesfully\n' "$target"
            return
        fi
    done

}
