#!/usr/bin/env bash

function deploy_symlinks() {

    local prog_name="$1"

    local arrayBinary=()
    readarray -t arrayBinary < <(find "${CS_ROOT}/${prog_name}/bin" -type f)

    printf -- '==> Making symlinks\n'

    for b in ${arrayBinary[@]} ; do
        b_name=$(basename $b)
        ln -sf "$b" "${CS_BIN_DIR}/${b_name}"
        printf -- '%s -> %s\n' "$b" "${CS_BIN_DIR}/${b_name}"
    done

}

function unpack_tarball() {

    local pkg_name_ver="$1"
    local pkg_name="${pkg_name_ver%-*}"

    if [[ -d "${CS_ROOT}/${pkg_name}" ]] ; then
        printf -- 'Package already installed. Overwrite? [y|n] '
        read -r ans

        if [[ "$ans" != "y" ]] ; then
            return
        fi

        printf -- '==> Reinstalling %s\n' "$pkg_name"

    else
        printf -- '==> Installing %s\n' "$pkg_name"
    fi

    printf -- '%s -> %s\n' "${pkg_name_ver}.tar.xz"  "${CS_ROOT}/${pkg_name}"

    tar -xf "${CS_PACKAGES_DIR}/${pkg_name_ver}.tar.xz" -C "${CS_ROOT}"

    deploy_symlinks ${pkg_name}

}
