#!/usr/bin/env bash

function tools_list() {

    local symlinkArray=()
    readarray -t symlinkArray < <(find "${CS_ROOT}/bin" -type l)

    for b in "${symlinkArray[@]}" ; do
        printf -- '%s\n' "$(basename $b)"
    done

}
